# Generated by Django 5.1.3 on 2024-12-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaterreno',
            name='actividad',
            field=models.CharField(blank=True, default='por_definir', max_length=200, null=True),
        ),
    ]
