# Generated by Django 5.1.3 on 2025-03-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0007_salidaterreno_docente_responsable_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaterreno',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
