# Generated by Django 5.1.3 on 2024-11-18 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'asignaturas',
            },
        ),
        migrations.CreateModel(
            name='UsersAcademy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(blank=True, choices=[(1, '1 Semestre'), (2, '2 Semestre'), (3, '3 Semestre'), (4, '4 Semestre'), (5, '5 Semestre'), (6, '6 Semestre'), (7, '7 Semestre'), (8, '8 Semestre')], null=True)),
                ('sede', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('jornada', models.CharField(blank=True, max_length=100, null=True)),
                ('asignaturas_inscritas', models.ManyToManyField(blank=True, related_name='alumnos_inscritos', to='core.asignatura')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usersAcademy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('perfil', models.CharField(choices=[('A', 'Alumno'), ('C', 'Coordinador'), ('D', 'Docente')], max_length=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios')),
                ('rut', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('ap_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('ap_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('fnacimiento', models.DateField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usersmetadata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Metadata',
                'verbose_name_plural': 'Users Metadata',
            },
        ),
    ]
