# Generated by Django 5.1.3 on 2024-12-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nombreseccion_alter_usersacademy_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalidaAcademica',
        ),
    ]
