# Generated by Django 5.1.3 on 2024-12-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_salidaacademica'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersacademy',
            name='anno_ingreso',
            field=models.IntegerField(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045), (2046, 2046), (2047, 2047), (2048, 2048), (2049, 2049)], null=True, verbose_name='Año de Ingreso'),
        ),
        migrations.AddField(
            model_name='usersacademy',
            name='cod_carrera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersacademy',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersacademy',
            name='correoduoc',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersacademy',
            name='subtipo_ingreso',
            field=models.CharField(blank=True, choices=[('REGULAR', 'REGULAR'), ('INTERNO', 'INTERNO'), ('RAP-IES', 'RAP-IES'), ('otro', 'otro')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersacademy',
            name='tipo_ingreso',
            field=models.CharField(blank=True, choices=[('ALUMNO DE INICIO', 'ALUMNO DE INICIO'), ('ALUMNO DE ADMISIÓN ESPECIAL', 'ALUMNO DE ADMISIÓN ESPECIAL')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersacademy',
            name='username_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersmetadata',
            name='conctacto_sostenedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
