# Generated by Django 5.1.3 on 2024-12-05 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usersacademy',
            options={'verbose_name': 'User Academy', 'verbose_name_plural': 'Users Academy'},
        ),
        migrations.AddField(
            model_name='asignatura',
            name='coordinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_coordinadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semestre',
            field=models.IntegerField(choices=[(1, '1 Semestre'), (2, '2 Semestre'), (3, '3 Semestre'), (4, '4 Semestre'), (5, '5 Semestre'), (6, '6 Semestre'), (7, '7 Semestre'), (8, '8 Semestre')], default=1),
        ),
        migrations.CreateModel(
            name='SalidaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('asignaturas', models.ManyToManyField(related_name='salidas_academicas', to='core.asignatura')),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas_academicas_coordinadas', to=settings.AUTH_USER_MODEL)),
                ('estudiantes', models.ManyToManyField(related_name='salidas_academicas_participadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cupo', models.IntegerField(default=30)),
                ('asignatura', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.asignatura')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones_impartidas', to=settings.AUTH_USER_MODEL)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nombreseccion')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'db_table': 'secciones',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('RETIRADA', 'Retirada')], max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.seccion')),
            ],
            options={
                'unique_together': {('alumno', 'seccion')},
            },
        ),
    ]
