# Generated by Django 5.1.3 on 2024-12-05 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_delete_salidaacademica'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalidaTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EJECUTADO', 'Ejecutado'), ('POR_EJECUTAR', 'Por Ejecutar'), ('por_definir', 'Por definir')], default='por_definir', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('numero_cuenta', models.IntegerField()),
                ('semestre', models.IntegerField(blank=True, choices=[(1, '1 Semestre'), (2, '2 Semestre'), (3, '3 Semestre'), (4, '4 Semestre'), (5, '5 Semestre'), (6, '6 Semestre'), (7, '7 Semestre'), (8, '8 Semestre')], null=True)),
                ('anio', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3000)])),
                ('semana', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3000)])),
                ('actividad', models.CharField(blank=True, choices=[('actividad_1', 'Actividad 1'), ('actividad_2', 'Actividad 2'), ('actividad_3', 'Actividad 3'), ('actividad_4', 'Actividad 4'), ('por_definir', 'Por definir')], default='por_definir', max_length=100, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('dias', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('noches', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('lugar_ejecucion', models.CharField(max_length=60)),
                ('exp_aprendizaje', models.CharField(blank=True, choices=[('EA-1', 'EA-1'), ('EA-2', 'EA-2'), ('EA-3', 'EA-3'), ('EA-4', 'EA-4'), ('examen_transversal', 'Examen Transversal'), ('por_definir', 'Por definir')], default='por_definir', max_length=20, null=True)),
                ('num_salida', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('no_requiere', 'No Requiere')], max_length=30, null=True)),
                ('observaciones', models.TextField()),
                ('semaforo', models.CharField(blank=True, choices=[('verde', 'Confirmado'), ('amarillo', 'Viable'), ('rojo', 'Poco fiable'), ('gris', 'Por confirmar')], max_length=20, null=True)),
                ('asignaturas', models.ManyToManyField(blank=True, related_name='salidas_terreno', to='core.asignatura')),
                ('diasemana', models.ManyToManyField(blank=True, to='coordinador.diasemana')),
                ('docentes_apoyo', models.ManyToManyField(blank=True, related_name='salidas_terreno_apoyo', to='core.usersmetadata')),
                ('secciones', models.ManyToManyField(blank=True, to='core.seccion')),
            ],
            options={
                'verbose_name': 'Salida Terreno',
                'verbose_name_plural': 'Salidas Terreno',
            },
        ),
    ]
