# Generated by Django 5.1.3 on 2025-03-14 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0003_alter_salidaterreno_dias_alter_salidaterreno_noches'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaterreno',
            name='cantidad_alumnos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='iframe_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='linkmapa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='nro_oc_servicios',
            field=models.CharField(blank=True, default='No Aplica', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='nro_oc_transporte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='observaciones_programacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='proveedor_servicios',
            field=models.CharField(blank=True, default='No Aplica', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='proveedor_sugerido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='proveedor_transporte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='totalhoras',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='valor_servicios',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
        migrations.AddField(
            model_name='salidaterreno',
            name='valor_transporte',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='estado',
            field=models.CharField(choices=[('EJECUTADO', 'Ejecutado'), ('POR_EJECUTAR', 'Por Ejecutar'), ('SUSPENDIDO', 'Suspendido'), ('por_definir', 'Por definir')], default='por_definir', max_length=20),
        ),
        migrations.AlterField(
            model_name='salidaterreno',
            name='numero_cuenta',
            field=models.IntegerField(unique=True),
        ),
    ]
