# Generated by Django 5.1.3 on 2025-03-14 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0004_salidaterreno_cantidad_alumnos_and_more'),
        ('core', '0005_alter_usersacademy_nom_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaterreno',
            name='docente_reemplazo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_terreno_apoyo_reemplazo', to='core.usersmetadata'),
        ),
    ]
