# Generated by Django 5.1.3 on 2025-03-14 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0005_salidaterreno_docente_reemplazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaterreno',
            name='numero_cuenta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
