# Generated by Django 5.1.3 on 2025-03-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0006_alter_salidaterreno_numero_cuenta'),
        ('core', '0005_alter_usersacademy_nom_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaterreno',
            name='docente_responsable_doc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_terreno_docente_responsable', to='core.usersmetadata'),
        ),
    ]
